### ISSUE TITLE
Allow to access to added series

### ISSUE THREAD

**Issue by stsdc** [lcallarec/live-chart#14]
I'm adding a few series and have to create another `ArrayList` to manipulate them. Would be nice to have an access to `chart.series`.

```vala
        private Gee.ArrayList<Serie> series = new Gee.ArrayList<Serie>();
```

Use case:

```vala
    public void update (int serie_number, double value) {
        chart.add_value (chart.series[serie_number], value);
    }
```

**Comment by lcallarec** [comment]
I could give access to `series` private chart array list, but it may lead to inconsistencies / bugs if you manually add or remove series.

To match your use case, I could add an `chart.add_value` method which take the `serie_number` instead of the `Series` :

```vala
public void add_value_by_index(int serie_index, double value) {
    add_value(series[serie_index], value);
}
```

Another option would be to have access to some kind of read-only array list ;

```vala
    public void update (int serie_number, double value) {
        Gee.List<Serie> series = chart.get_ro_series();
        chart.add_value (series.get(serie_number, value);
    }
```

IMHO, the both options match your use case. The first is straight forward, the second is more versatile (hence, it could resolves more use cases) but requires a bit more code on your side.

What do you think ?

**Comment by stsdc** [comment]
I created `serie_list = new  Gee.ArrayList<LiveChart.Serie> ();` and it works, but, well, now I have two lists with same content 😅
`chart.add_value_by_index` would be cool

**Comment by lcallarec** [comment]
https://github.com/lcallarec/live-chart/releases/tag/1.5.1

Please let me know when it works on your side.

Thanks !

**Comment by stsdc** [comment]
works really nice

thank You!
